In [83]:
import tensorflow as tf
import numpy as np

# Set the 'legacy' option to an integer value
np.set_printoptions(legacy='1.13')

different data structures => 0D, 1D, 2D and more than 2D

In [84]:
a=tf.constant(5)
a

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [85]:
a=tf.constant([8,1,6])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([8, 1, 6], dtype=int32)>

In [86]:
a=tf.constant([[8,1,6],[1,2,3]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[8, 1, 6],
       [1, 2, 3]], dtype=int32)>

In [87]:
a=tf.constant([[[8,1,6],[1,2,3]],[[80,10,60],[10,20,30]]])
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 8,  1,  6],
        [ 1,  2,  3]],

       [[80, 10, 60],
        [10, 20, 30]]], dtype=int32)>

Different Operation

In [91]:
a = tf.constant([3,5])
b = tf.constant([1,4])

In [92]:
#sum
c = tf.add(a,b)
c.numpy()

array([4, 9], dtype=int32)

In [93]:
# subtract
d= tf.subtract(a,b)
d.numpy()

array([2, 1], dtype=int32)

In [94]:
#multiplya
a_1 = tf.constant([[2,3],[0,5]])
b_1 = tf.constant([[1,3],[6,4]])

ew = tf.multiply(a_1,b_1)
ew

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  9],
       [ 0, 20]], dtype=int32)>

In [95]:
mm = tf.matmul(a_1, b_1)
mm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 18],
       [30, 20]], dtype=int32)>

In [96]:
#divide
div = tf.divide(a_1,b_1)
div

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 2.  ,  1.  ],
       [ 0.  ,  1.25]])>

In [97]:
# broadcasting
a_2 = tf.constant([1,2,3])
b_2 = tf.constant(4) # 4 => [4,4,4]

c_2 = a_2 * b_2
c_2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  8, 12], dtype=int32)>

## Reshape

In [99]:
a = tf.constant([3,4,5,6,1,2])
a.shape

TensorShape([6])

In [100]:
b = tf.reshape(a, shape=(2,3,1))
b

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[3],
        [4],
        [5]],

       [[6],
        [1],
        [2]]], dtype=int32)>

In [101]:
# add demension
a = tf.constant([3,4,5,6,1,2])
a.shape

TensorShape([6])

In [102]:
b = tf.expand_dims(a, axis=-1)
b.shape

TensorShape([6, 1])

In [103]:
a = tf.constant([[3,4],[2,5]])
a.shape

TensorShape([2, 2])

In [104]:
b = tf.square(a)
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 16],
       [ 4, 25]], dtype=int32)>

In [105]:
c= tf.sqrt(tf.cast(a, dtype=tf.float32))
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.7320508,  2.       ],
       [ 1.4142135,  2.2360678]], dtype=float32)>

# Min , Max, Mean ,STD

In [113]:
a = tf.constant([[3,4],[2,5]], dtype=tf.float32)
a
a.numpy()

array([[ 3.,  4.],
       [ 2.,  5.]], dtype=float32)

In [107]:
min = tf.reduce_min(a, axis=1)
min

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [111]:
#numpy
a3= np.array([[3,4],[2,5]])
a3.mean()

3.5

In [115]:
avg = tf.reduce_mean(a)
avg.numpy()

3.5

In [117]:
avg = tf.reduce_mean(a, axis=0)
avg.numpy()

array([ 2.5,  4.5], dtype=float32)

In [118]:
avg = tf.reduce_mean(a, axis=1)
avg.numpy()

array([ 3.5,  3.5], dtype=float32)

In [119]:
std = tf.math.reduce_std(a)
std.numpy()

1.1180339